### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by VSPA-grp** [titomncl/Odin#35]
Every time I use the soft, I'm asking myself if there is a new update. So I check on the repo if a new stable version is released.

It would be nice if a pop-up can ask the user to update the soft when there is a new stable release.
If the user doesn't want to update, it saves the result and ask again seven or more days after, or never ask again.

**Comment by titomncl** [comment]
A solution of auto-update currently exists but some features had to be implemented. It only works with stable version, if you have a beta version, the auto-update will not, for now, update to the stable one.
