### ISSUE TITLE
Odin failed to start

### ISSUE THREAD

**Issue by VSPA-grp** [titomncl/Odin#60]
Hi,

I tried to run Odin but there was a fatal error detected.
![20210904_161416](https://user-images.githubusercontent.com/88336691/132495065-97f071e5-6533-4482-ac25-ae05988777ad.jpg)

Here is the log file:
[Odin.log](https://github.com/titomncl/Odin/files/7128175/Odin.log)

Thanks,
Teddy

**Comment by titomncl** [comment]
Hi!

Where you connected to internet while launching Odin?
If you weren't, I think that it was what it caused the issue.
It will be corrected in the next release.
