### ISSUE TITLE
Can't open my tools in maya 

### ISSUE THREAD

**Issue by savitar46** [titomncl/Odin#61]
Hello,

I tried to use Odin for my personnal project with my personnal tools but it appears that I can't open them nor access them through the script editor.

Here is the log from Maya:
```
2021-09-09 16:35:23 -- WARNING -- [Errno 2] No such file or directory: 'D:/PROJETS\\PROJETS\\CB\\odin.yaml'
# Warning: Odin : [Errno 2] No such file or directory: 'D:/PROJETS\\PROJETS\\CB\\odin.yaml' # 
# Error: RuntimeError: file X:\VSPA\DEV\main\Odin\odin\source\core\project.py line 118: No project 'PROJETS\CB' created in 'D:/PROJETS'. #
 ```

Thanks

**Comment by titomncl** [comment]
Hi!

I the problem is related to how Odin process the root path.
It will be corrected in the next release
